### ISSUE TITLE
How to define proto inside optional paremeters

### ISSUE THREAD

**Issue by gurofti** [single9/node-grpc-graphql-server#10]
Hi, How to define proto inside optional paremeters?

This is example not working

message RegisterRequest {
  string first_name = 1;
  optional int32 page_number = 2;

}

**Comment by single9** [comment]
This package does not support the **optional** and **required** since they have removed in Protocol Buffers 3.

**Comment by gurofti** [comment]
Thank you, How to send headers inside Autherization?

**Comment by single9** [comment]
I don't get it. Please provide more details.

**Comment by gurofti** [comment]
![image](https://user-images.githubusercontent.com/65256779/197466664-75a996f4-2ca7-44d3-b0d4-29b4b3ae3450.png)

![image](https://user-images.githubusercontent.com/65256779/197466784-f6e8d491-cd72-418f-9b46-effc85038fd9.png)

I not show headers controller inside "Authorization"

**Comment by single9** [comment]
Take a look: [Looks like you send request to GraphQL. This package use Apollo Server](https://github.com/single9/node-grpc-graphql-server#context)

**Comment by gurofti** [comment]
How to get headers in controller? 
I not see
![image](https://user-images.githubusercontent.com/65256779/197703094-f595a7aa-291f-428d-8d44-35ccc61fc5f8.png)
![image](https://user-images.githubusercontent.com/65256779/197703196-65a3b57f-43c8-4a45-86b0-13dbb8bcf0ba.png)

**Comment by single9** [comment]
Is this gRPC controller?
