### ISSUE TITLE
nestjs integration

### ISSUE THREAD

**Issue by apolonsoft** [single9/node-grpc-graphql-server#5]
Hi
Thanks for your great package.
i want to integrate your package into nestjs.
scenario: transport method  between mircroservices is grpc but they should send graphql to each other.
can you advise me?

**Comment by single9** [comment]
Hi,

Thanks for your first issue : D

You can build the server by this package and use [GraphQL client](https://www.npmjs.com/package/graphql-request) to send request to each other.

BTW, I think use grpc is enough. Why you want to use GraphQL to do the same thing?

**Comment by apolonsoft** [comment]
HI

> Thanks for your first issue : D
;)

here is my scenario

1) Microservice A creates request payload according to proto schema and sends it to microservice B
2) Microservice B catches this request in middleware
3) Middleware passes request's objects such as query, variables, extensions etc directly to the graphql processing function
4) Microservice B creates response payload according to proto schema and sends it back to the Microservice A
5) Microservice A works with the response data

current:
HTTP req -> apollo server -> gql underlying processing -> resolver

wanted:
gRPC req -> grpc-apollo-server -> gql underlying processing -> resolver

**Comment by single9** [comment]
Hmmm...

This package makes grpc and gql using same controller in the auto-generator mode. 

I think you can try to using [customize GraphQL schema and Resolver](https://github.com/single9/node-grpc-graphql-server#manually-graphql-schema-and-resolver) to do it.
